# Generated by Django 2.1.3 on 2018-11-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.CharField(choices=[('PC', 'Personal Computer'), ('PS4', 'Play Station 4'), ('XB1', 'XBox One')], default='', max_length=100)),
                ('genre', models.CharField(choices=[('act', 'Action'), ('adv', 'Adventure'), ('sp', 'Sports'), ('sho', 'Shooting'), ('mus', 'Musical'), ('fig', 'Fighting'), ('rac', 'Racing')], default='', max_length=100)),
                ('age_restriction', models.CharField(choices=[('Ao', 'AdultsOnly'), ('M', 'Mature'), ('T', 'Teen'), ('E', 'Everyone'), ('eC', 'EarlyChildhood')], default='', max_length=100)),
                ('game_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
