# Generated by Django 2.1.3 on 2018-11-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefinderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_restriction',
            field=models.CharField(choices=[(0, 'AdultsOnly'), (1, 'Mature'), (2, 'Teen'), (3, 'Everyone'), (4, 'EarlyChildhood')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.CharField(choices=[(0, 'Personal Computer'), (1, 'Play Station 4'), (2, 'XBox One')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[(0, 'Action'), (1, 'Adventure'), (2, 'Sports'), (3, 'Shooting'), (4, 'Musical'), (5, 'Fighting'), (6, 'Racing')], default='', max_length=100),
        ),
    ]
